# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20170823_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
